GET http://localhost:8081/userinfo
Accept: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDY2MDA0OTYsInVzZXJfbmFtZSI6ImFkbWluIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiJdLCJqdGkiOiJiMzMxZGRmNy00YTA0LTQ1ODMtYjY1OC1jNjdmZDZiNzIzMTMiLCJjbGllbnRfaWQiOiJjbGllbnQwMSIsInNjb3BlIjpbInJlYWQiXX0.KvlTF6GuDefbPFqSeI6C9AHgpEd70m8X6GknbsDDHd8
###
