server:
  port: 8080

# Logging
logging:
  level:
    com.example: debug
    org.springframework.security: debug

# oauth2
spring:
  security:
    oauth2:
      client:
        registration:
          my-oauth:
            provider: custom
            client-id: client01
            client-secret: secret01
            client-name: client01
            scope: read
            redirect-uri: http://localhost:8080/login/oauth2/code/my-oauth
            authorization-grant-type: authorization_code
            client-authentication-method: basic
        provider:
          custom:
            authorization-uri: http://localhost:8081/oauth/authorize
            token-uri: http://localhost:8081/oauth/token
            user-info-uri: http://localhost:8081/userinfo
            user-name-attribute: username
#            user-info-authentication-method: header
#            jwk-set-uri: http://localhost:8081/token_keys





